name: "Hello World"
description: "Greet someone and record the time"
inputs:
  spheron-token: # id of input
    description: "A spheron token for compute organization"
    required: true
  cluster-name:
    description: "The name of the cluster"
    required: true
  image: 
    description: "The docker image to run"
    required: true
  tag:
    description: "The tag of the docker image to run"
    required: false
    default: "latest"
  health-check-path:e
    description: "The path of health check endpoint"
    required: false
  health-check-port:
    description: "The port of health check endpoint"
    required: false
  instance-plan-name:
    description: "The name of the instance plan"
    required: true
  ports:
    description: "The ports to expose. Format: 80:8080,443:8443,..."
    required: false
  env:
    description: "The environment variables to set. Format: key1=value1,key2=value2,..."
    required: false
  secret-env:
    description: "The environment variables that need to be passed everythime."
    required: false
  commands: // remove from update
    description: "The commands to run. Format: command1,command2,..."
    required: false
  args: // remove from update
    description: "The arguments to pass to the command. Format: arg1,arg2,..."
    required: false
  region: // remove form update
    description: "The region to deploy to"
    required: false
    default: "any"
runs:
  using: "node16"
  main: "index.js"
