name: "Hello World"
description: "Greet someone and record the time"
inputs:
  spheron-token: # id of input
    description: "A spheron token for compute organization"
    required: true
  cluster-name:
    description: "The name of the cluster"
    required: true
  image-url:
    description: "The url of the docker image to run"
    required: true
  image:
    description: "The docker image to run"
    required: true
  tag:
    description: "The tag of the docker image to run"
    required: false
    default: "latest"
  health-check-path:
    description: "The path of health check endpoint"
    required: false
  health-check-port:
    description: "The port of health check endpoint"
    required: false
  instance-plan-name:
    description: "The name of the instance plan"
    required: true
runs:
  using: "node16"
  main: "index.js"
